import React, { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import axiosClient from '@/libraries/axiosClient';

function Products(props) {
  const { products } = props;
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {products.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {products.map((p) => (
            <Link
              style={{ height: '80px' }}
              key={p._id}
              href={`/product/get-static-props/${p._id}`}
            >
              <h1>{p.name}</h1>
            </Link>
          ))}
        </div>
      ) : (
        <small>Không có sản phẩm</small>
      )}
    </>
  );
}

export default Products;

// getStaticProps - Static-Side Generation
// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: true,
//   };
// }

export async function getStaticProps(req) {
  try {
    const response = await axiosClient.get('/products');

    return {
      props: {
        products: response.data.payload,
      },

      // revalidate: 10,
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}
